import mongoose, { Schema } from "mongoose"

/**
 * BrowserSession Model (formerly Session)
 *
 * Collection: "browser_sessions"
 *
 * Groups a conversation thread. Represents a single user task/session that may span multiple requests.
 * Enables long-term memory, chat history persistence, and proper state management across client reloads.
 *
 * - Created on first POST /api/agent/interact without sessionId
 * - Status tracks lifecycle: active → completed/failed/interrupted
 * - All accesses scoped by tenantId
 *
 * Domain-Aware Sessions:
 * - domain: Root domain extracted from URL (e.g., "google.com")
 * - title: Session title with format "{domain}: {task description}"
 * - isRenamed: Flag to prevent auto-title updates when user manually renames
 *
 * Tab-Scoped Sessions (Feb 2026):
 * - Sessions are now scoped to browser tabs on the client (one session per tabId)
 * - tabId: Chrome tab ID (debug metadata only, not stable across browser restarts)
 * - url: Current URL of the session (updated when navigation occurs within the same tab)
 * - domain: Current root domain (updated when cross-domain navigation occurs)
 * - Sessions persist across domain navigations within the same tab
 * - The interact route updates url/domain when they change during an active session
 *
 * Tenant ID: userId (normal mode) or organizationId (organization mode)
 */

export type SessionStatus = "active" | "completed" | "failed" | "interrupted" | "archived"

export interface IBrowserSession extends mongoose.Document {
  sessionId: string // UUID (generated by server, not _id)
  userId: string // User who owns the session
  tenantId: string // userId or organizationId
  tabId?: number // Chrome tab ID (debug metadata only, not stable across restarts)
  url: string // Current URL (updated on navigation within the same tab session)
  domain?: string // Current root domain (updated on cross-domain navigation)
  title?: string // Session title with format "{domain}: {task description}"
  isRenamed?: boolean // Whether user manually renamed the session
  status: SessionStatus // Session status
  createdAt: Date // When session was created
  updatedAt: Date // Last update timestamp
  metadata?: {
    // Additional session metadata
    taskType?: string
    initialQuery?: string
    initialUrl?: string // Original URL when session was created (for history)
    initialDomain?: string // Original domain when session was created
    initialTabId?: number // Original tab ID when session was created
    [key: string]: unknown
  }
}

const BrowserSessionSchema = new Schema<IBrowserSession>(
  {
    sessionId: {
      type: String,
      required: true,
      unique: true,
    },
    userId: {
      type: String,
      required: true,
      index: true,
    },
    tenantId: {
      type: String,
      required: true,
      index: true,
    },
    tabId: {
      type: Number,
      required: false,
      index: true, // Index for faster tab-based lookups
    },
    url: {
      type: String,
      required: true,
    },
    domain: {
      type: String,
      required: false,
      index: true,
    },
    title: {
      type: String,
      required: false,
    },
    isRenamed: {
      type: Boolean,
      required: false,
      default: false,
    },
    status: {
      type: String,
      enum: ["active", "completed", "failed", "interrupted", "archived"],
      default: "active",
      required: true,
      index: true,
    },
    metadata: {
      type: Schema.Types.Mixed,
      required: false,
    },
  },
  {
    timestamps: true,
    collection: "browser_sessions", // Explicit collection name
  }
)

// Indexes for efficient queries
// Note: sessionId already has unique: true which creates an index automatically
BrowserSessionSchema.index({ userId: 1, createdAt: -1 })
BrowserSessionSchema.index({ tenantId: 1, status: 1, createdAt: -1 })
// Domain-aware session indexes
BrowserSessionSchema.index({ tenantId: 1, domain: 1, status: 1 })
BrowserSessionSchema.index({ domain: 1, status: 1, updatedAt: -1 })
// Tab-scoped session index (for finding sessions by tab)
BrowserSessionSchema.index({ tenantId: 1, tabId: 1, status: 1 })

export const BrowserSession =
  mongoose.models.BrowserSession ||
  mongoose.model<IBrowserSession>("BrowserSession", BrowserSessionSchema, "browser_sessions")
