import mongoose, { Schema } from "mongoose"

/**
 * Session Model (Task 3)
 *
 * Groups a conversation thread. Represents a single user task/session that may span multiple requests.
 * Enables long-term memory, chat history persistence, and proper state management across client reloads.
 *
 * - Created on first POST /api/agent/interact without sessionId
 * - Status tracks lifecycle: active → completed/failed/interrupted
 * - All accesses scoped by tenantId
 *
 * Tenant ID: userId (normal mode) or organizationId (organization mode)
 */

export type SessionStatus = "active" | "completed" | "failed" | "interrupted" | "archived"

export interface ISession extends mongoose.Document {
  sessionId: string // UUID (generated by server, not _id)
  userId: string // User who owns the session
  tenantId: string // userId or organizationId
  url: string // Initial URL where the task started
  status: SessionStatus // Session status
  createdAt: Date // When session was created
  updatedAt: Date // Last update timestamp
  metadata?: {
    // Additional session metadata
    taskType?: string
    initialQuery?: string
    [key: string]: unknown
  }
}

const SessionSchema = new Schema<ISession>(
  {
    sessionId: {
      type: String,
      required: true,
      unique: true,
    },
    userId: {
      type: String,
      required: true,
      index: true,
    },
    tenantId: {
      type: String,
      required: true,
      index: true,
    },
    url: {
      type: String,
      required: true,
    },
    status: {
      type: String,
      enum: ["active", "completed", "failed", "interrupted", "archived"],
      default: "active",
      required: true,
      index: true,
    },
    metadata: {
      type: Schema.Types.Mixed,
      required: false,
    },
  },
  {
    timestamps: true,
  }
)

// Indexes for efficient queries
// Note: sessionId already has unique: true which creates an index automatically
SessionSchema.index({ userId: 1, createdAt: -1 })
SessionSchema.index({ tenantId: 1, status: 1, createdAt: -1 })

export const Session =
  mongoose.models.Session || mongoose.model<ISession>("Session", SessionSchema)
