import mongoose, { Schema } from "mongoose"

/**
 * Snapshot Model (Improvement 3: DOM Bloat Management)
 *
 * Stores DOM snapshots separately from messages to prevent MongoDB bloat.
 * Messages reference snapshots via snapshotId instead of storing full DOM.
 *
 * - Created when a message needs DOM context
 * - Referenced by Message.snapshotId
 * - Can be cleaned up after a retention period
 * - All accesses scoped by tenantId
 *
 * Tenant ID: userId (normal mode) or organizationId (organization mode)
 */

export interface ISnapshot extends mongoose.Document {
  snapshotId: string // UUID (generated by server, not _id)
  sessionId: string // Links to parent Session
  tenantId: string // userId or organizationId
  domSnapshot: string // Full DOM snapshot (can be large: 50KB-500KB)
  url: string // URL where snapshot was taken
  timestamp: Date // When snapshot was created
  metadata?: {
    // Additional metadata
    messageId?: string // Associated message ID (if applicable)
    [key: string]: unknown
  }
}

const SnapshotSchema = new Schema<ISnapshot>(
  {
    snapshotId: {
      type: String,
      required: true,
      unique: true,
    },
    sessionId: {
      type: String,
      required: true,
      index: true,
    },
    tenantId: {
      type: String,
      required: true,
      index: true,
    },
    domSnapshot: {
      type: String,
      required: true,
    },
    url: {
      type: String,
      required: true,
    },
    timestamp: {
      type: Date,
      required: true,
      default: Date.now,
      index: true,
    },
    metadata: {
      type: Schema.Types.Mixed,
      required: false,
    },
  },
  {
    timestamps: true,
  }
)

// Indexes for efficient queries
// Note: snapshotId already has unique: true which creates an index automatically
SnapshotSchema.index({ sessionId: 1, timestamp: -1 })
SnapshotSchema.index({ tenantId: 1, timestamp: -1 })
// Index for cleanup: find old snapshots
SnapshotSchema.index({ tenantId: 1, timestamp: 1 })

export const Snapshot =
  mongoose.models.Snapshot || mongoose.model<ISnapshot>("Snapshot", SnapshotSchema)
