import mongoose, { Schema } from "mongoose"

/**
 * Task Model
 *
 * Task metadata for Thin Client action loop (Task 3).
 * Tracks multi-step tasks executed by the extension.
 *
 * - Created on first POST /api/agent/interact without taskId
 * - Status tracks lifecycle: active → completed/failed/interrupted (Task 3)
 * - Extended status for orchestrator: planning → executing → verifying → correcting → completed/failed/interrupted (Task 6)
 * - All accesses scoped by tenantId
 *
 * Tenant ID: userId (normal mode) or organizationId (organization mode)
 */

// Task type classification for routing (File-Based Tasks & Chat Mode)
export type TaskType =
  | "web_only"      // Existing: requires browser interaction
  | "web_with_file" // Web task with file context
  | "chat_only"     // No browser needed, direct response

// File attachment stored on task
export interface TaskAttachment {
  id: string              // UUID
  filename: string        // Original filename
  mimeType: string        // e.g., "text/csv", "application/pdf"
  s3Key?: string          // S3 storage key (if uploaded)
  size: number            // File size in bytes
  extractedContent?: string    // Parsed text content
  extractedMetadata?: Record<string, unknown>  // Title, pages, etc.
  uploadedAt: Date
}

// Task result for chat-only tasks
export interface TaskResult {
  summary: string
  data?: Record<string, unknown>
  generatedAt: Date
}

// Task 6: Extended status enum for orchestrator
export type TaskStatus =
  | "active" // Legacy status (backward compatibility)
  | "completed"
  | "failed"
  | "interrupted"
  | "planning" // Task 6: Planning phase
  | "executing" // Task 6: Executing plan
  | "verifying" // Task 6: Verifying results
  | "correcting" // Task 6: Correcting errors
  | "awaiting_user" // Blocker detected, waiting for user input

// Blocker type matches blocker-detection.ts BlockerType
export type TaskBlockerType =
  | "login_failure"
  | "mfa_required"
  | "captcha"
  | "cookie_consent"
  | "modal_decision"
  | "missing_info"
  | "rate_limit"
  | "session_expired"
  | "access_denied"
  | "page_error"

// Resolution method matches blocker-detection.ts ResolutionMethod
export type TaskResolutionMethod =
  | "user_action_on_web"
  | "provide_in_chat"
  | "auto_retry"
  | "alternative_action"

// Required field for user input
export interface TaskBlockerRequiredField {
  name: string
  label: string
  type: "text" | "password" | "email" | "code"
  description?: string
}

// Blocker context stored on task when paused
export interface TaskBlockerContext {
  type: TaskBlockerType
  description: string
  userMessage?: string
  resolutionMethods: TaskResolutionMethod[]
  requiredFields?: TaskBlockerRequiredField[]
  matchedPattern?: string
  confidence?: number
  retryAfterSeconds?: number
  /** Step index where blocker occurred */
  pausedAtStep?: number
  /** URL where blocker was detected */
  pausedAtUrl?: string
}

// Task 6: Plan step structure
export interface PlanStep {
  index: number // Step index in plan
  description: string // High-level step description (e.g., "Enter email address")
  reasoning?: string // Why this step is needed
  toolType: "DOM" | "SERVER" | "MIXED" // Tool type needed for this step
  status: "pending" | "active" | "completed" | "failed" // Step status
  expectedOutcome?: {
    // What should happen after this step (for verification)
    description?: string
    [key: string]: unknown
  }
}

// Task 6: Plan structure
export interface TaskPlan {
  steps: PlanStep[] // Array of plan step objects
  currentStepIndex: number // Current position in plan (default: 0)
  createdAt: Date // When plan was created
}

export interface ITask extends mongoose.Document {
  taskId: string // UUID (generated by server, not _id)
  tenantId: string // userId or organizationId
  userId: string // User who initiated the task
  url: string // Active tab URL when task was created (optional for chat_only)
  query: string // User query/instructions
  status: TaskStatus
  // Task type classification (File-Based Tasks & Chat Mode)
  taskType?: TaskType
  // File attachments for task context
  attachments?: TaskAttachment[]
  // Result for chat-only tasks
  result?: TaskResult
  // Task 6: Action plan (optional)
  plan?: TaskPlan
  // Phase 4 Task 8: Hierarchical plan (sub-tasks) when decomposition was applied
  hierarchicalPlan?: Record<string, unknown>
  // Task 8: Retry limits for self-correction
  maxRetriesPerStep?: number // Max retries per step (default: 3)
  consecutiveFailures?: number // Track consecutive failures (default: 0)
  /** Semantic loop prevention: consecutive successful verifications without task_completed (default: 0). When >= 5, task is failed with reflection message. */
  consecutiveSuccessWithoutTaskComplete?: number
  // Task 1 (Web Search): Web search results for task context
  webSearchResult?: {
    searchQuery: string // The query used for search
    results: Array<{
      title: string
      url: string
      snippet: string // Brief summary from search result
      relevanceScore?: number // Optional relevance score (0-1)
    }>
    summary: string // LLM-generated summary of search results
    timestamp: Date // When search was performed
  }
  // Task-scoped memory for storing intermediate results
  memory?: Record<string, unknown>
  // Blocker pause/resume fields
  /** When task was paused due to blocker */
  pausedAt?: Date
  /** Blocker context when task is in awaiting_user status */
  blockerContext?: TaskBlockerContext
  /** User-provided resolution data (from chat or web) */
  userResolutionData?: Record<string, unknown>
  // Aggregate execution metrics (Task 3)
  metrics?: {
    totalSteps: number // Total number of actions executed
    totalRequestDuration: number // Sum of all request durations in milliseconds
    totalRagDuration: number // Sum of all RAG retrieval durations in milliseconds
    totalLlmDuration: number // Sum of all LLM call durations in milliseconds
    totalTokenUsage: {
      promptTokens: number
      completionTokens: number
    }
    averageRequestDuration: number // Average request duration per step
  }
  createdAt: Date
  updatedAt: Date
}

const TaskSchema = new Schema<ITask>(
  {
    taskId: {
      type: String,
      required: true,
      unique: true,
    },
    tenantId: {
      type: String,
      required: true,
    },
    userId: {
      type: String,
      required: true,
    },
    url: {
      type: String,
      required: false, // Optional for chat_only tasks
      default: "",
    },
    query: {
      type: String,
      required: true,
    },
    status: {
      type: String,
      enum: [
        "active", // Legacy status (backward compatibility)
        "completed",
        "failed",
        "interrupted",
        "planning", // Task 6: Planning phase
        "executing", // Task 6: Executing plan
        "verifying", // Task 6: Verifying results
        "correcting", // Task 6: Correcting errors
        "awaiting_user", // Blocker detected, waiting for user input
      ],
      default: "active",
      required: true,
    },
    // Task type classification (File-Based Tasks & Chat Mode)
    taskType: {
      type: String,
      enum: ["web_only", "web_with_file", "chat_only"],
      default: "web_only",
      required: false,
    },
    // File attachments for task context
    attachments: [
      {
        id: { type: String, required: true },
        filename: { type: String, required: true },
        mimeType: { type: String, required: true },
        s3Key: { type: String, required: false },
        size: { type: Number, required: true },
        extractedContent: { type: String, required: false },
        extractedMetadata: { type: Schema.Types.Mixed, required: false },
        uploadedAt: { type: Date, required: true, default: Date.now },
      },
    ],
    // Result for chat-only tasks
    result: {
      summary: { type: String, required: false },
      data: { type: Schema.Types.Mixed, required: false },
      generatedAt: { type: Date, required: false },
    },
    // Task 6: Action plan (optional)
    plan: {
      steps: [
        {
          index: { type: Number, required: true },
          description: { type: String, required: true },
          reasoning: { type: String, required: false },
          toolType: {
            type: String,
            enum: ["DOM", "SERVER", "MIXED"],
            required: true,
          },
          status: {
            type: String,
            enum: ["pending", "active", "completed", "failed"],
            required: true,
          },
          expectedOutcome: {
            type: Schema.Types.Mixed,
            required: false,
          },
        },
      ],
      currentStepIndex: {
        type: Number,
        required: false,
        default: 0,
      },
      createdAt: {
        type: Date,
        required: false,
        default: Date.now,
      },
    },
    // Phase 4 Task 8: Hierarchical plan (sub-tasks)
    hierarchicalPlan: {
      type: Schema.Types.Mixed,
      required: false,
    },
    // Task 8: Retry limits for self-correction
    maxRetriesPerStep: {
      type: Number,
      required: false,
      default: 3,
    },
    consecutiveFailures: {
      type: Number,
      required: false,
      default: 0,
    },
    consecutiveSuccessWithoutTaskComplete: {
      type: Number,
      required: false,
      default: 0,
    },
    // Task-scoped memory for storing intermediate results
    memory: {
      type: Schema.Types.Mixed,
      required: false,
      default: {},
    },
    // Blocker pause/resume fields
    pausedAt: {
      type: Date,
      required: false,
    },
    blockerContext: {
      type: {
        type: String,
        enum: [
          "login_failure",
          "mfa_required",
          "captcha",
          "cookie_consent",
          "modal_decision",
          "missing_info",
          "rate_limit",
          "session_expired",
          "access_denied",
          "page_error",
        ],
        required: true,
      },
      description: {
        type: String,
        required: true,
      },
      userMessage: {
        type: String,
        required: false,
      },
      resolutionMethods: [
        {
          type: String,
          enum: ["user_action_on_web", "provide_in_chat", "auto_retry", "alternative_action"],
        },
      ],
      requiredFields: [
        {
          name: { type: String, required: true },
          label: { type: String, required: true },
          type: { type: String, enum: ["text", "password", "email", "code"], required: true },
          description: { type: String, required: false },
        },
      ],
      matchedPattern: {
        type: String,
        required: false,
      },
      confidence: {
        type: Number,
        required: false,
      },
      retryAfterSeconds: {
        type: Number,
        required: false,
      },
      pausedAtStep: {
        type: Number,
        required: false,
      },
      pausedAtUrl: {
        type: String,
        required: false,
      },
    },
    userResolutionData: {
      type: Schema.Types.Mixed,
      required: false,
    },
    // Task 1 (Web Search): Web search results for task context
    webSearchResult: {
      searchQuery: {
        type: String,
        required: false,
      },
      results: [
        {
          title: {
            type: String,
            required: false,
          },
          url: {
            type: String,
            required: false,
          },
          snippet: {
            type: String,
            required: false,
          },
          relevanceScore: {
            type: Number,
            required: false,
          },
        },
      ],
      summary: {
        type: String,
        required: false,
      },
      timestamp: {
        type: Date,
        required: false,
      },
    },
    metrics: {
      totalSteps: {
        type: Number,
        required: false,
        default: 0,
      },
      totalRequestDuration: {
        type: Number,
        required: false,
        default: 0,
      },
      totalRagDuration: {
        type: Number,
        required: false,
        default: 0,
      },
      totalLlmDuration: {
        type: Number,
        required: false,
        default: 0,
      },
      totalTokenUsage: {
        promptTokens: {
          type: Number,
          required: false,
          default: 0,
        },
        completionTokens: {
          type: Number,
          required: false,
          default: 0,
        },
      },
      averageRequestDuration: {
        type: Number,
        required: false,
        default: 0,
      },
    },
  },
  {
    timestamps: true,
  }
)

// Index for efficient tenant + task lookups
TaskSchema.index({ tenantId: 1, taskId: 1 }, { unique: true })
TaskSchema.index({ tenantId: 1, status: 1 })
TaskSchema.index({ tenantId: 1, userId: 1 })
// Index for finding paused tasks awaiting user input
TaskSchema.index({ tenantId: 1, userId: 1, status: 1, pausedAt: -1 })

export const Task =
  mongoose.models.Task || mongoose.model<ITask>("Task", TaskSchema)
