import mongoose, { Schema } from "mongoose"

/**
 * Task Model
 *
 * Task metadata for Thin Client action loop (Task 3).
 * Tracks multi-step tasks executed by the extension.
 *
 * - Created on first POST /api/agent/interact without taskId
 * - Status tracks lifecycle: active → completed/failed/interrupted
 * - All accesses scoped by tenantId
 *
 * Tenant ID: userId (normal mode) or organizationId (organization mode)
 */
export type TaskStatus = "active" | "completed" | "failed" | "interrupted"

export interface ITask extends mongoose.Document {
  taskId: string // UUID (generated by server, not _id)
  tenantId: string // userId or organizationId
  userId: string // User who initiated the task
  url: string // Active tab URL when task was created
  query: string // User query/instructions
  status: TaskStatus
  createdAt: Date
  updatedAt: Date
}

const TaskSchema = new Schema<ITask>(
  {
    taskId: {
      type: String,
      required: true,
      unique: true,
    },
    tenantId: {
      type: String,
      required: true,
    },
    userId: {
      type: String,
      required: true,
    },
    url: {
      type: String,
      required: true,
    },
    query: {
      type: String,
      required: true,
    },
    status: {
      type: String,
      enum: ["active", "completed", "failed", "interrupted"],
      default: "active",
      required: true,
    },
  },
  {
    timestamps: true,
  }
)

// Index for efficient tenant + task lookups
TaskSchema.index({ tenantId: 1, taskId: 1 }, { unique: true })
TaskSchema.index({ tenantId: 1, status: 1 })
TaskSchema.index({ tenantId: 1, userId: 1 })

export const Task =
  mongoose.models.Task || mongoose.model<ITask>("Task", TaskSchema)
